sudo: required

language: generic

services:
  - docker

script:
  - docker build -t jaschweder/azure .

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push jaschweder/azure;
