FROM {IMAGE_FROM}

RUN apt-get update -y \
    && apt-get install git \
    --no-install-recommends \
    --no-install-suggests \
    -y

RUN cd /usr/src \
    && git clone -b {XDEBUG_BRANCH} --depth 1 https://github.com/xdebug/xdebug \
    && cd xdebug \
    && phpize \
    && ./configure \
    && make \
    && make install \
    && docker-php-ext-enable xdebug \
    && rm -rf /usr/src/xdebug

RUN cd /usr/local/bin \
    && curl -sSL https://getcomposer.org/composer.phar -o composer \
    && chmod a+x composer

RUN composer global require phpunit/phpunit

RUN rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove \
    && apt-get autoclean

WORKDIR /src

CMD ["phpunit"]
